#!/bin/bash
# Trading-Handbook daily incremental update (GitHub-primary, runs on this host's crontab).
# SELF-HEALING: "work to do" is detected by distill/page EXISTENCE, not by an index diff, so a
# fetch/classify/generate/gate failure is simply retried on the next run (never orphaned).
# Bodies (data/raw, data/distill) stay LOCAL (gitignored); only pages + index.json are pushed.
set -uo pipefail
cd /home/claudeuser/trading-handbook-work || exit 1
export PATH="/usr/local/bin:/usr/bin:/bin:$HOME/.local/bin:$PATH"
LOG=data/daily.log
SENT=data/.daily_inprogress          # left behind only by a crashed/timed-out run
ts(){ date -u +"%Y-%m-%d %H:%M:%S"; }
log(){ echo "[$(ts)] $*" | tee -a "$LOG"; }
GIT="git -c user.name=Pulsar Bot -c user.email=noreply@anthropic.com"

log "===== daily start ====="

# index.json is regenerated by enumerate; drop any crashed-mid-run copy so pull can't soft-lock.
git checkout -- data/index.json 2>/dev/null || true

# Guard against clobbering EXTERNAL edits, but self-recover from our OWN crash (sentinel present).
DIRTY=$(git status --porcelain -- foundations crossing cheat-sheet docs.json)
RECOVER=0
if [ -n "$DIRTY" ]; then
  if [ -f "$SENT" ]; then RECOVER=1; log "recovering leftover work from a prior interrupted run"
  else log "ABORT: tracked content dirty and no in-progress sentinel (external edits?)"; exit 0; fi
fi

# Only pull when clean; in recovery the tree has uncommitted tracked edits that would block rebase.
if [ "$RECOVER" -eq 0 ]; then
  git pull --rebase -q 2>>"$LOG" || { log "ABORT: git pull failed"; exit 1; }
fi
touch "$SENT"

python3 scripts/pulsar/enumerate_album.py >>"$LOG" 2>&1 || { log "enumerate failed"; rm -f "$SENT"; exit 1; }

# Never let the public index SHRINK (a truncated enumerate must not drop articles).
python3 - >>"$LOG" 2>&1 <<'PY'
import json, subprocess
new = json.load(open("data/index.json"))
try: old = json.loads(subprocess.check_output(["git", "show", "HEAD:data/index.json"]).decode())
except Exception: old = []
if len(new) < len(old):
    open("data/index.json", "w").write(json.dumps(old, ensure_ascii=False, indent=2))
    print("index shrank (%d<%d) -> kept committed copy" % (len(new), len(old)))
PY

# NEW = album articles with NO local distill record (fetch/classify failures retry here daily).
NEW=$(python3 - <<'PY'
import json, os
print(",".join(str(a["pos"]) for a in json.load(open("data/index.json"))
                if not os.path.exists("data/distill/%s.json" % a["msgid"])))
PY
)
CNT=$(echo "$NEW" | tr ',' '\n' | grep -c .)

# MISSING = page-worthy non-dup distill records with no page file (Pass B self-heals these).
MISSING=$(python3 - <<'PY'
import json, glob, re, os
def slug(d):
    if d.get("slug_override"): return d["slug_override"]
    fw = (d.get("source", {}) or {}).get("framework")
    b = fw if fw and fw.lower() not in ("null", "none", "") else d["title"]
    s = re.sub(r'[^a-zA-Z0-9]+', '-', (b or "")).strip('-').lower()
    return s or "art-%s" % d["pos"]
m = 0
for f in glob.glob("data/distill/*.json"):
    d = json.load(open(f))
    if d.get("page_worthy") and d.get("rating") in ("⚡", "🔧") and not d.get("dup_of"):
        if not os.path.exists("foundations/%s/%s.md" % (d["zone"], slug(d))): m += 1
print(m)
PY
)
TREE_DIRTY=$(git status --porcelain -- foundations crossing cheat-sheet docs.json data/index.json)

if [ "$CNT" -eq 0 ] && [ "$MISSING" -eq 0 ] && [ -z "$TREE_DIRTY" ]; then
  log "nothing to do (0 new, 0 missing pages, clean tree)"; rm -f "$SENT"; exit 0
fi
log "work: fetch=$CNT missing-pages=$MISSING dirty=$([ -n "$TREE_DIRTY" ] && echo y || echo n)"

if [ "$CNT" -gt 0 ]; then
  log "fetch/classify pos $NEW"
  python3 scripts/pulsar/fetch_article.py --poslist "$NEW" --workers 3 >>"$LOG" 2>&1
  python3 scripts/pulsar/distill_pass_a.py --workers 3 >>"$LOG" 2>&1
  # conservative dedup: new record matching an existing framework / normalized title -> dup_of.
  python3 - "$NEW" >>"$LOG" 2>&1 <<'PY'
import json, glob, re, sys
newpos = {int(x) for x in sys.argv[1].split(",") if x.strip()}
def norm(t): return re.sub(r'[^一-鿿a-zA-Z0-9]', '', re.sub(r'^[A-Z]+\s*\d*\s*\|', '', t or ''))
recs = [json.load(open(f)) for f in glob.glob("data/distill/*.json")]
old = [d for d in recs if d.get("pos") not in newpos]
for d in recs:
    if d.get("pos") not in newpos or d.get("dup_of"): continue
    fw = (d.get("source", {}) or {}).get("framework")
    for o in old:
        ofw = (o.get("source", {}) or {}).get("framework")
        if (fw and ofw and fw.strip().lower() == ofw.strip().lower()) or norm(d["title"]) == norm(o["title"]):
            d["dup_of"] = o["msgid"]
            json.dump(d, open("data/distill/%s.json" % d["msgid"], "w"), ensure_ascii=False, indent=2)
            print("daily-dedup: pos%s dup_of pos%s" % (d["pos"], o["pos"])); break
PY
  python3 scripts/pulsar/fix_collisions.py >>"$LOG" 2>&1 || true
fi

python3 scripts/pulsar/distill_pass_b.py --workers 3 >>"$LOG" 2>&1   # generates only missing pages
python3 scripts/add_fingerprint.py >>"$LOG" 2>&1
python3 scripts/pulsar/asciiflow_to_mermaid.py --workers 2 >>"$LOG" 2>&1 || true
python3 scripts/gen_overviews.py >>"$LOG" 2>&1
python3 scripts/gen_nav.py >>"$LOG" 2>&1
python3 scripts/pulsar/number_audit.py >>"$LOG" 2>&1 || true        # advisory (logs flags)

$GIT add foundations/ crossing/ cheat-sheet/ bridge-to-vla/ docs.json data/index.json 2>>"$LOG"
if git diff --cached --name-only | grep -q '^data/\(raw\|distill\)/'; then
  log "ABORT: refusing to commit raw/distill bodies"; git reset -q; rm -f "$SENT"; exit 1
fi
if [ -z "$(git diff --cached --name-only)" ]; then log "nothing staged"; rm -f "$SENT"; exit 0; fi

# Hard gate: on failure keep the work STAGED + sentinel so the next run recovers and retries.
if ! python3 scripts/handbook_audit.py >>"$LOG" 2>&1; then
  log "GATE FAILED — staged, not pushing; next run will retry"; exit 1
fi

$GIT commit -q -m "daily: sync QuantML corpus [$(date -u +%Y-%m-%d)] (+$CNT new, $MISSING healed)" >>"$LOG" 2>&1
if $GIT push -q >>"$LOG" 2>&1; then
  log "PUSHED (+$CNT new, $MISSING healed)"; rm -f "$SENT"
else
  # remote advanced under us -> rebase the new commit and retry once
  if git pull --rebase -q >>"$LOG" 2>&1 && $GIT push -q >>"$LOG" 2>&1; then
    log "PUSHED after rebase (+$CNT new)"; rm -f "$SENT"
  else log "push FAILED — next run will retry"; exit 1; fi
fi
log "===== daily done ====="
